# version

services:
  backend:
    image: my-go-app
    build:
      context: ./
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"
    ports:
      - "8080:8080"
  db:
    image: postgres:17.0
    env_file: "postgres.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/migrations/up/:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data


volumes:
  db-data: